# Generated by Django 4.1 on 2022-09-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topping_one",
                    models.CharField(max_length=50, verbose_name="Topping One"),
                ),
                (
                    "topping_two",
                    models.CharField(max_length=50, verbose_name="Topping Two"),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("1", "Small"), ("2", "Medium"), ("3", "Large")],
                        max_length=50,
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
