# Generated by Django 4.1 on 2022-09-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="topping1",
            field=models.CharField(max_length=30, verbose_name="Topping_1"),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="topping2",
            field=models.CharField(max_length=30, verbose_name="Topping_2"),
        ),
        migrations.AlterField(
            model_name="size",
            name="title",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                max_length=10,
                verbose_name="Size",
            ),
        ),
    ]
