# Generated by Django 4.1 on 2022-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0002_alter_pizza_topping1_alter_pizza_topping2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="size",
            field=models.CharField(
                choices=[("1", "Small"), ("2", "Medium"), ("3", "Large")],
                max_length=50,
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="topping1",
            field=models.CharField(max_length=50, verbose_name="Topping One"),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="topping2",
            field=models.CharField(max_length=50, verbose_name="Topping Two"),
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
