# Generated by Django 4.1 on 2022-09-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0003_alter_pizza_size_alter_pizza_topping1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                max_length=50,
                verbose_name="",
            ),
        ),
    ]
